// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_MONSTERINFO_GAME_PROTOCOL_H_
#define FLATBUFFERS_GENERATED_MONSTERINFO_GAME_PROTOCOL_H_

#include "flatbuffers/flatbuffers.h"

namespace Game {
namespace Protocol {

struct Vec3;

struct Monster_Collection;

struct Monster_info;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3() {
    memset(this, 0, sizeof(Vec3));
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Monster_Collection FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_DATA = 4
  };
  const flatbuffers::Vector<flatbuffers::Offset<Monster_info>> *data() const {
    return GetPointer<const flatbuffers::Vector<flatbuffers::Offset<Monster_info>> *>(VT_DATA);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyOffset(verifier, VT_DATA) &&
           verifier.VerifyVector(data()) &&
           verifier.VerifyVectorOfTables(data()) &&
           verifier.EndTable();
  }
};

struct Monster_CollectionBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_data(flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Monster_info>>> data) {
    fbb_.AddOffset(Monster_Collection::VT_DATA, data);
  }
  explicit Monster_CollectionBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  Monster_CollectionBuilder &operator=(const Monster_CollectionBuilder &);
  flatbuffers::Offset<Monster_Collection> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Monster_Collection>(end);
    return o;
  }
};

inline flatbuffers::Offset<Monster_Collection> CreateMonster_Collection(
    flatbuffers::FlatBufferBuilder &_fbb,
    flatbuffers::Offset<flatbuffers::Vector<flatbuffers::Offset<Monster_info>>> data = 0) {
  Monster_CollectionBuilder builder_(_fbb);
  builder_.add_data(data);
  return builder_.Finish();
}

inline flatbuffers::Offset<Monster_Collection> CreateMonster_CollectionDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const std::vector<flatbuffers::Offset<Monster_info>> *data = nullptr) {
  return Game::Protocol::CreateMonster_Collection(
      _fbb,
      data ? _fbb.CreateVector<flatbuffers::Offset<Monster_info>>(*data) : 0);
}

struct Monster_info FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_ID = 4,
    VT_HP = 6,
    VT_ANIMATOR = 8,
    VT_DIRX = 10,
    VT_DIRZ = 12,
    VT_POSITION = 14,
    VT_ROTATION = 16
  };
  int32_t id() const {
    return GetField<int32_t>(VT_ID, 0);
  }
  int32_t hp() const {
    return GetField<int32_t>(VT_HP, 0);
  }
  int32_t animator() const {
    return GetField<int32_t>(VT_ANIMATOR, 0);
  }
  float dirX() const {
    return GetField<float>(VT_DIRX, 0.0f);
  }
  float dirZ() const {
    return GetField<float>(VT_DIRZ, 0.0f);
  }
  const Vec3 *position() const {
    return GetStruct<const Vec3 *>(VT_POSITION);
  }
  const Vec3 *rotation() const {
    return GetStruct<const Vec3 *>(VT_ROTATION);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<int32_t>(verifier, VT_ID) &&
           VerifyField<int32_t>(verifier, VT_HP) &&
           VerifyField<int32_t>(verifier, VT_ANIMATOR) &&
           VerifyField<float>(verifier, VT_DIRX) &&
           VerifyField<float>(verifier, VT_DIRZ) &&
           VerifyField<Vec3>(verifier, VT_POSITION) &&
           VerifyField<Vec3>(verifier, VT_ROTATION) &&
           verifier.EndTable();
  }
};

struct Monster_infoBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_id(int32_t id) {
    fbb_.AddElement<int32_t>(Monster_info::VT_ID, id, 0);
  }
  void add_hp(int32_t hp) {
    fbb_.AddElement<int32_t>(Monster_info::VT_HP, hp, 0);
  }
  void add_animator(int32_t animator) {
    fbb_.AddElement<int32_t>(Monster_info::VT_ANIMATOR, animator, 0);
  }
  void add_dirX(float dirX) {
    fbb_.AddElement<float>(Monster_info::VT_DIRX, dirX, 0.0f);
  }
  void add_dirZ(float dirZ) {
    fbb_.AddElement<float>(Monster_info::VT_DIRZ, dirZ, 0.0f);
  }
  void add_position(const Vec3 *position) {
    fbb_.AddStruct(Monster_info::VT_POSITION, position);
  }
  void add_rotation(const Vec3 *rotation) {
    fbb_.AddStruct(Monster_info::VT_ROTATION, rotation);
  }
  explicit Monster_infoBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  Monster_infoBuilder &operator=(const Monster_infoBuilder &);
  flatbuffers::Offset<Monster_info> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Monster_info>(end);
    return o;
  }
};

inline flatbuffers::Offset<Monster_info> CreateMonster_info(
    flatbuffers::FlatBufferBuilder &_fbb,
    int32_t id = 0,
    int32_t hp = 0,
    int32_t animator = 0,
    float dirX = 0.0f,
    float dirZ = 0.0f,
    const Vec3 *position = 0,
    const Vec3 *rotation = 0) {
  Monster_infoBuilder builder_(_fbb);
  builder_.add_rotation(rotation);
  builder_.add_position(position);
  builder_.add_dirZ(dirZ);
  builder_.add_dirX(dirX);
  builder_.add_animator(animator);
  builder_.add_hp(hp);
  builder_.add_id(id);
  return builder_.Finish();
}

}  // namespace Protocol
}  // namespace Game

#endif  // FLATBUFFERS_GENERATED_MONSTERINFO_GAME_PROTOCOL_H_
