// automatically generated by the FlatBuffers compiler, do not modify


#ifndef FLATBUFFERS_GENERATED_PLAYER_MYGAME_PLAYER_H_
#define FLATBUFFERS_GENERATED_PLAYER_MYGAME_PLAYER_H_

#include "flatbuffers/flatbuffers.h"

namespace MyGame {
namespace Player {

struct Vec3;

struct Player;

FLATBUFFERS_MANUALLY_ALIGNED_STRUCT(4) Vec3 FLATBUFFERS_FINAL_CLASS {
 private:
  float x_;
  float y_;
  float z_;

 public:
  Vec3() {
    memset(this, 0, sizeof(Vec3));
  }
  Vec3(float _x, float _y, float _z)
      : x_(flatbuffers::EndianScalar(_x)),
        y_(flatbuffers::EndianScalar(_y)),
        z_(flatbuffers::EndianScalar(_z)) {
  }
  float x() const {
    return flatbuffers::EndianScalar(x_);
  }
  float y() const {
    return flatbuffers::EndianScalar(y_);
  }
  float z() const {
    return flatbuffers::EndianScalar(z_);
  }
};
FLATBUFFERS_STRUCT_END(Vec3, 12);

struct Player FLATBUFFERS_FINAL_CLASS : private flatbuffers::Table {
  enum {
    VT_POS = 4,
    VT_NAME = 6,
    VT_HP = 8
  };
  const Vec3 *pos() const {
    return GetStruct<const Vec3 *>(VT_POS);
  }
  const flatbuffers::String *name() const {
    return GetPointer<const flatbuffers::String *>(VT_NAME);
  }
  int16_t hp() const {
    return GetField<int16_t>(VT_HP, 400);
  }
  bool Verify(flatbuffers::Verifier &verifier) const {
    return VerifyTableStart(verifier) &&
           VerifyField<Vec3>(verifier, VT_POS) &&
           VerifyOffset(verifier, VT_NAME) &&
           verifier.VerifyString(name()) &&
           VerifyField<int16_t>(verifier, VT_HP) &&
           verifier.EndTable();
  }
};

struct PlayerBuilder {
  flatbuffers::FlatBufferBuilder &fbb_;
  flatbuffers::uoffset_t start_;
  void add_pos(const Vec3 *pos) {
    fbb_.AddStruct(Player::VT_POS, pos);
  }
  void add_name(flatbuffers::Offset<flatbuffers::String> name) {
    fbb_.AddOffset(Player::VT_NAME, name);
  }
  void add_hp(int16_t hp) {
    fbb_.AddElement<int16_t>(Player::VT_HP, hp, 400);
  }
  explicit PlayerBuilder(flatbuffers::FlatBufferBuilder &_fbb)
        : fbb_(_fbb) {
    start_ = fbb_.StartTable();
  }
  PlayerBuilder &operator=(const PlayerBuilder &);
  flatbuffers::Offset<Player> Finish() {
    const auto end = fbb_.EndTable(start_);
    auto o = flatbuffers::Offset<Player>(end);
    return o;
  }
};

inline flatbuffers::Offset<Player> CreatePlayer(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Vec3 *pos = 0,
    flatbuffers::Offset<flatbuffers::String> name = 0,
    int16_t hp = 400) {
  PlayerBuilder builder_(_fbb);
  builder_.add_name(name);
  builder_.add_pos(pos);
  builder_.add_hp(hp);
  return builder_.Finish();
}

inline flatbuffers::Offset<Player> CreatePlayerDirect(
    flatbuffers::FlatBufferBuilder &_fbb,
    const Vec3 *pos = 0,
    const char *name = nullptr,
    int16_t hp = 400) {
  return MyGame::Player::CreatePlayer(
      _fbb,
      pos,
      name ? _fbb.CreateString(name) : 0,
      hp);
}

inline const MyGame::Player::Player *GetPlayer(const void *buf) {
  return flatbuffers::GetRoot<MyGame::Player::Player>(buf);
}

inline const MyGame::Player::Player *GetSizePrefixedPlayer(const void *buf) {
  return flatbuffers::GetSizePrefixedRoot<MyGame::Player::Player>(buf);
}

inline bool VerifyPlayerBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifyBuffer<MyGame::Player::Player>(nullptr);
}

inline bool VerifySizePrefixedPlayerBuffer(
    flatbuffers::Verifier &verifier) {
  return verifier.VerifySizePrefixedBuffer<MyGame::Player::Player>(nullptr);
}

inline void FinishPlayerBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MyGame::Player::Player> root) {
  fbb.Finish(root);
}

inline void FinishSizePrefixedPlayerBuffer(
    flatbuffers::FlatBufferBuilder &fbb,
    flatbuffers::Offset<MyGame::Player::Player> root) {
  fbb.FinishSizePrefixed(root);
}

}  // namespace Player
}  // namespace MyGame

#endif  // FLATBUFFERS_GENERATED_PLAYER_MYGAME_PLAYER_H_
