// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Game.Protocol
{

using global::System;
using global::FlatBuffers;

public struct Item_Collection : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static Item_Collection GetRootAsItem_Collection(ByteBuffer _bb) { return GetRootAsItem_Collection(_bb, new Item_Collection()); }
  public static Item_Collection GetRootAsItem_Collection(ByteBuffer _bb, Item_Collection obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p.bb_pos = _i; __p.bb = _bb; }
  public Item_Collection __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public Item_info? Data(int j) { int o = __p.__offset(4); return o != 0 ? (Item_info?)(new Item_info()).__assign(__p.__indirect(__p.__vector(o) + j * 4), __p.bb) : null; }
  public int DataLength { get { int o = __p.__offset(4); return o != 0 ? __p.__vector_len(o) : 0; } }

  public static Offset<Item_Collection> CreateItem_Collection(FlatBufferBuilder builder,
      VectorOffset dataOffset = default(VectorOffset)) {
    builder.StartObject(1);
    Item_Collection.AddData(builder, dataOffset);
    return Item_Collection.EndItem_Collection(builder);
  }

  public static void StartItem_Collection(FlatBufferBuilder builder) { builder.StartObject(1); }
  public static void AddData(FlatBufferBuilder builder, VectorOffset dataOffset) { builder.AddOffset(0, dataOffset.Value, 0); }
  public static VectorOffset CreateDataVector(FlatBufferBuilder builder, Offset<Item_info>[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateDataVectorBlock(FlatBufferBuilder builder, Offset<Item_info>[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static void StartDataVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static Offset<Item_Collection> EndItem_Collection(FlatBufferBuilder builder) {
    int o = builder.EndObject();
    return new Offset<Item_Collection>(o);
  }
};


}
